OPENNLP-142 Improved exception messages, they now contain a little context which makes it possible to locate the line in the training data

git-svn-id: https://svn.apache.org/repos/asf/incubator/opennlp/trunk@1129141 13f79535-47bb-0310-9956-ffa450edef68

+  private static String errorTokenWithContext(String sentence[], int index) {
+    
+    StringBuilder errorString = new StringBuilder();
+    
+    // two token before
+    if (index > 1)
+      errorString.append(sentence[index -2]).append(" ");
+    
+    if (index > 0)
+      errorString.append(sentence[index -1]).append(" ");
+    
+    // token itself
+    errorString.append("###");
+    errorString.append(sentence[index]);
+    errorString.append("###").append(" ");
+    
+    // two token after
+    if (index + 1 < sentence.length)
+      errorString.append(sentence[index + 1]).append(" ");
+
+    if (index + 2 < sentence.length)
+      errorString.append(sentence[index + 2]);
+    
+    return errorString.toString();
+  }
+  
-          throw new IOException("Found unexpected annotation " + parts[pi] + " while handling a name sequence.");
+          throw new IOException("Found unexpected annotation" + 
+              " while handling a name sequence: " + errorTokenWithContext(parts, pi));
-          throw new IOException("Missing a name type: " + parts[pi]);
+          throw new IOException("Missing a name type: " + errorTokenWithContext(parts, pi));
-          throw new IOException("Found unexpected annotation " + parts[pi] + ".");
+          throw new IOException("Found unexpected annotation: " + errorTokenWithContext(parts, pi));
