HDFS-12683. DFSZKFailOverController re-order logic for logging Exception. Contributed by Bharat Viswanadham.

-      LOG.error("The failover controller encounters runtime error: " + rte);
-      throws HadoopIllegalArgumentException, IOException, InterruptedException {
+      throws Exception {
-          + "ZooKeeper is running.");
+          + "ZooKeeper is running.", ke);
-    if (args.length > 0) {
-      if ("-formatZK".equals(args[0])) {
-        boolean force = false;
-        boolean interactive = true;
-        for (int i = 1; i < args.length; i++) {
-          if ("-force".equals(args[i])) {
-            force = true;
-          } else if ("-nonInteractive".equals(args[i])) {
-            interactive = false;
-          } else {
-            badArg(args[i]);
+    try {
+      if (args.length > 0) {
+        if ("-formatZK".equals(args[0])) {
+          boolean force = false;
+          boolean interactive = true;
+          for (int i = 1; i < args.length; i++) {
+            if ("-force".equals(args[i])) {
+              force = true;
+            } else if ("-nonInteractive".equals(args[i])) {
+              interactive = false;
+            } else {
+              badArg(args[i]);
+            }
+          return formatZK(force, interactive);
-        return formatZK(force, interactive);
-      } else {
-        badArg(args[0]);
+        else {
+          badArg(args[0]);
+        }
+    } catch (Exception e){
+      LOG.error("The failover controller encounters runtime error", e);
+      throw e;
-    initRPC();
-    initHM();
-    startRPC();
+      initRPC();
+      initHM();
+      startRPC();
+    } catch (Exception e) {
+      LOG.error("The failover controller encounters runtime error: ", e);
+      throw e;
