HADOOP-14982. Clients using FailoverOnNetworkExceptionRetry can go into a loop if they're used without authenticating with kerberos in HA env (pbacsko via rkanter)

+import javax.security.sasl.SaslException;
+
-  
+
+  void failsWithSASLExceptionTenTimes() throws SaslException;
+
