YARN-4655. Log uncaught exceptions/errors in various thread pools in YARN. Contributed by Sidharta Seethana.

-import java.util.concurrent.ExecutionException;
-import java.util.concurrent.FutureTask;
+import org.apache.hadoop.util.concurrent.HadoopScheduledThreadPoolExecutor;
-      sched = new DelServiceSchedThreadPoolExecutor(
+      sched = new HadoopScheduledThreadPoolExecutor(
-      sched = new DelServiceSchedThreadPoolExecutor(
+      sched = new HadoopScheduledThreadPoolExecutor(
-  private static class DelServiceSchedThreadPoolExecutor extends
-      ScheduledThreadPoolExecutor {
-    public DelServiceSchedThreadPoolExecutor(int corePoolSize,
-        ThreadFactory threadFactory) {
-      super(corePoolSize, threadFactory);
-    }
-
-    @Override
-    protected void afterExecute(Runnable task, Throwable exception) {
-      if (task instanceof FutureTask<?>) {
-        FutureTask<?> futureTask = (FutureTask<?>) task;
-        if (!futureTask.isCancelled()) {
-          try {
-            futureTask.get();
-          } catch (ExecutionException ee) {
-            exception = ee.getCause();
-          } catch (InterruptedException ie) {
-            exception = ie;
-          }
-        }
-      }
-      if (exception != null) {
-        LOG.error("Exception during execution of task in DeletionService",
-          exception);
-      }
-    }
-  }
-
