HADOOP-16683. Disable retry of FailoverOnNetworkExceptionRetry in case of wrapped AccessControlException. Contributed by Adam Antal

-      } else if (e instanceof AccessControlException) {
+      } else if (e instanceof AccessControlException ||
+              hasWrappedAccessControlException(e)) {
+
+  private static boolean hasWrappedAccessControlException(Exception e) {
+    Throwable throwable = e;
+    while (!(throwable instanceof AccessControlException) &&
+        throwable.getCause() != null) {
+      throwable = throwable.getCause();
+    }
+    return throwable instanceof AccessControlException;
+  }

INS31 INS83 INS83 INS39 INS42 INS44 INS8 INS43 INS42 INS60 INS61 INS41 INS42 INS43 INS59 INS27 INS8 INS62 INS42 INS42 INS42 INS38 INS27 INS21 INS42 INS43 INS36 INS32 INS33 INS7 INS42 INS62 INS42 INS42 INS42 INS32 INS27 INS42 INS43 INS42 INS42 MOV62 INS32 INS42 INS42 INS42