HADOOP-14982. Clients using FailoverOnNetworkExceptionRetry can go into a loop if they're used without authenticating with kerberos in HA env (pbacsko via rkanter)

+import javax.security.sasl.SaslException;
+
+import org.ietf.jgss.GSSException;
+      if (isSaslFailure(e)) {
+          return new RetryAction(RetryAction.RetryDecision.FAIL, 0,
+                  "SASL failure");
+      }
+
-  
+
+
+  private static boolean isSaslFailure(Exception e) {
+      Throwable current = e;
+      do {
+          if (current instanceof SaslException) {
+            return true;
+          }
+          current = current.getCause();
+      } while (current != null);
+
+      return false;
+  }

INS26 INS26 INS40 INS40 INS31 INS83 INS83 INS39 INS42 INS44 INS8 INS43 INS42 INS60 INS19 INS41 INS25 INS42 INS43 INS59 INS8 INS27 INS9 INS32 INS8 INS42 INS42 INS42 INS25 INS21 INS42 INS33 INS42 INS42 INS41 INS62 INS8 INS7 INS14 INS42 INS43 INS41 INS42 INS32 INS43 INS40 INS34 INS45 INS42 INS9 INS42 INS42 INS42